name: flutter_application_1
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  url_launcher:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  share_plus: ^7.2.2
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-new.png"

flutter_native_splash: 
  android: true
  ios: true
  color: "272727"
  image: assets/images/levelup-logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/levelup-logo.png
